### ISSUE TITLE
USER STORY: Login with Username and Password

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/MyOfficeSpace#1]
As a **user** I want to be able to **login to my account**

## Acceptance Criteria

1. User's Account must be exist in database
2. Username and password must be provided
3. Provided credentials must match and be case sensitive
4. User will be redirected to User Dashboard.

## Tasks

- [x] Create User table
- [x] Create Login Screen
- [x] Enable reCAPTCHA
- [x] Create test login account
- [x] Test login function
