### ISSUE TITLE
USER STORY: Booking a Meeting Room

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/MyOfficeSpace#10]
As a **user** I would like to book a meeting room with or without an Office Space

## Acceptance Criteria

1. User is able to search for Meeting Rooms
2. Book Meeting room for specific times
3. No Double bookings is allowed

## Tasks

- [ ] Add Meeting Rooms to tables
- [ ] Add function to allow bookings for specific times
- [ ] Ensure double bookings are not possible
- [ ] Testing Meeting Room Function
