### ISSUE TITLE
USER STORY: Create an account

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/MyOfficeSpace#12]
As a **non registered user** I want to be able to create an account on the system.

## Acceptance Criteria

1. User is able to create an account
2. User has confirmed their email address
3. User is able to login after confirming their email address

## Tasks

- [x] Create Sign Up Page
- [x] Create Sign Up Form
- [x] Enable function to send confirmation email
- [x] Enable account once email address is confirmed.

**Comment by desousamario85** [comment]
Imported with Allauth django module
