### ISSUE TITLE
USER STORY: Cancel Meeting Rooms

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/MyOfficeSpace#15]
As a **User** I want to be able to cancel my Meeting Room booking

## Acceptance Criteria

1. User is able to cancel meeting room booking they have selected
2. Meeting room is available to select from same time and date it was originally booked for.
3. 

## Tasks

- [x] Create cancel Meeting booking function
- [x] Create pop up model
- [x] Confirm Meeting Room booking is cancelled
- [x] Confirm Meeting Room can be rebook for the same date and time.
