### ISSUE TITLE
USER STORY: Create data model

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/MyOfficeSpace#2]
As a **developer** I need to **data model** for my application

## Acceptance Criteria
When data model has been defined and implemented in DB

## Tasks

- [x] Create data model
- [x] Create Tables
- [x] Add columns to tables
- [x] Setup primary keys
- [x] Create foreign keys
