### ISSUE TITLE
USER STORY: UI/UX Design

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/MyOfficeSpace#4]
As a **user** i want a user friendly UI/UX design for the site.

## Acceptance Criteria

1. Corporate Branding color scheme
2. Readable

## Tasks

- [x] Review corporate color schemes
- [x] Make sample logo
- [x] Select font types

**Comment by desousamario85** [comment]
Colours and Main font selected

**Comment by desousamario85** [comment]
PT-Serif and Roboto fonts are selected
