### ISSUE TITLE
USER STORY: Booking an Office Space

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/MyOfficeSpace#5]
As a **user** i want to be **able to book** an office space which are available on the selected date

## Acceptance Criteria

1. Selecting Date to book an Office Space
2. Select Office Type
3. Book Office Space
4. Confirm that selected office space is not available for booking.

## Tasks

- [x] Insert date picker
- [x] Create function to select all office space not booked
- [x] Create function to book office space for the logged in user
- [x] Ensure booked office is display in the users dashboard.
