### ISSUE TITLE
USER STORY: Cancel a selected booked Office Space

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/MyOfficeSpace#6]
As a **user** I want to  **cancel my booked office space** which will allow the office space to be available for selection for the date I had it booked for.

## Acceptance Criteria

1. I can selected an office space
2. Select to Cancel the booking
3. get confirmation that the office space was cancelled

## Tasks

- [x] Create function to remove booked office space from user.
- [x] Create Pop up modal to allow users to delete booking
- [x] Test that office space is available for selection on the selected date
