### ISSUE TITLE
USER STORY: Multi-Factor authentication

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/MyOfficeSpace#9]
As a **User** I want to **enable 2FA on my account** which will make my account more secure.

## Acceptance Criteria

1. Allow User to Enable 2FA
2. Ensure 2FA is Enable for selected user
3. User is login to account with 2FA enabled.

## Tasks

- [x] Integrate 2FA Module
- [ ] Check configuration on allowing users to 2FA by choice
- [ ]  Test 2FA function

**Comment by desousamario85** [comment]
reCaptcha was installed , but no included on pages yet.

**Comment by desousamario85** [comment]
Won't be implement due to time constraints.
